### ISSUE TITLE
Remove *.db from repo?

### ISSUE THREAD

**Issue by Rotbjorn** [ProNinjaGamin0/ninjaBot#2]
Exact files:
 - `afkDatabase.db`
 - `tradeBanned.db`

**Comment by swithinpais** [comment]
Those files are used for the ?afk and ?tradeban command respectively. Why should they be removed?

**Comment by Rotbjorn** [comment]
I thought it made more sense to generate those files when you start the bot for the first time.

**Comment by swithinpais** [comment]
Probably yea, im just lazy.
